### ISSUE TITLE
Depth quality algorithm

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#17]
To check for threshold depths using correlation and intensity

**Comment by kurtisanstey** [comment]
@jklymak 

Still struggling to iterate over numbered variables without using a for loop. I want something like n=range(4), then in my loop just put corr{n}, etc. without having to nest it in a 'for i in n:' loop.

Very rough looking process, but it works fine (wrote it for one beam and then copied it four times, so everything repeats itself a bunch...). Check out the last two cells:
https://github.com/kurtisanstey/project/blob/master/archive/data_management/MAT_data_quality.ipynb

**Comment by jklymak** [comment]
I'm not 100% following your question:

```python
corr0_avg = np.empty([d_len,t_len])                   # empty array for binned correlation values
corr1_avg = np.empty([d_len,t_len])                   
corr2_avg = np.empty([d_len,t_len])                 
corr3_avg = np.empty([d_len,t_len])                   
intens0_avg = np.empty([d_len,t_len])                 # empty array for binned intensity values
intens1_avg = np.empty([d_len,t_len])                
intens2_avg = np.empty([d_len,t_len])                 
intens3_avg = np.empty([d_len,t_len]) 
```

can be rewritten:

```python
corr_avg = []
for i in range(4):
    corr_avg += [np.empty([d_len,t_len])]
    intens_avg += [np.empty([d_len,t_len])]

# use it:
for i in range(4): 
   corr_avg[i][:, n] = data
```

**Comment by kurtisanstey** [comment]
That's kind of what I was getting at, and I can definitely use that to make things more concise. It's annoying not having ever had courses in programming, as I feel I'm missing some basics, and always looking up simple processes.

I was hoping there's a way to not use a 'for i in range(4):' loop to cycle through the corr_avg[i] index. Like making some list with corr1, corr2, etc. and you can just use corr{n} or something similar to call them all, the same as the loop would do but without having to nest it. I just want fewer loops!

**Comment by jklymak** [comment]
You can also make it a 3-D matrix if that is better:

`corr_avg = np.empty([4, d_len, t_len])`

you may end up looping sometimes, but maybe it will be a bit more concise.  However, don't be dogmatic about removing loops, particularly small ones.  Looping 4 times is fine.  Even looping over one dimension is fine if it saves a headache.  The problems are usually double loops on big data sets.  For four beams I wouldn't make a 3-D axes just because 3-D axes can be confusing in their own right, whereas a list of four 2-D axes is pretty easy.

**Comment by kurtisanstey** [comment]
OK. That's very helpful. As long as it works, and runs fairly quickly!

**Comment by kurtisanstey** [comment]
Working, but should revisit if there is time, later. Use a conservative depth estimate, for now.
