### ISSUE TITLE
Committee presentation

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#18]
Presentation slides with:
- [x] List of progress
- [x] Previous MSc outline
- [x] Thesis outline

**Comment by kurtisanstey** [comment]
Presentation outline has been drafted, and adding content now that everything has been updated with the new data and process to deal with data gaps.

- [ ] Send Jody a finished draft on Friday/Monday.

**Comment by kurtisanstey** [comment]
![image](https://user-images.githubusercontent.com/57200139/108949143-b7361680-7618-11eb-82a8-cf9dbd9aca65.png)

**Comment by kurtisanstey** [comment]
This is meant be supplementary to talking points, and focus on the structure/general content of my thesis, not specific findings.

It contains:
- Recap of program.
- Progress since last meeting.
- The MSc regarding Barkley Canyon by Burrier (December 2019).
- Outline of thesis contents.
- Timeline.

Anything to add/remove? I'll go over it again after our meeting, and before the committee meeting.

**Comment by jklymak** [comment]
OK< this has a *lot* of "what you did" and some technical detail, but very little actual science. It would be nice if you discussed the importance of your problem and what you will do to move it forward with this data set.  A long set of bullets describing a thesis is not very effective, and should be introductory material.  

Please do *not* think of this as "Results", "Discussion".  That is *not* how we present science despite what you may have learnt elsewhere.  Many students do this: "Here are a bunch of plots", with no explanation (other than describing the plots), and then a "discussion" of the plots completely disjoint.  Almost everything you are calling "Discussion" are actually results.  Everything you are calling results are just plots that you will use to bolster the points you are making in what you are calling "Discussion".  "Discussion" is actually for caveats, what you would do next time, implications, and importance.  

Some idea of the science you have seen would be helpful at this point.  You should be moving beyond "assembling the plots" to telling science stories with the plots.  So, what are those stories?  Ideally you would have a couple before Friday.  Hopefully they are ones you laid out in your intro as important ones.

**Comment by kurtisanstey** [comment]
@jklymak, thank you, this is what I'm looking for. 

The point of this meeting (in my mind) is to get your advice as to how a thesis should be structured, because I'm uncertain. Looking at Burrier's thesis, it is a bit 'Results' and 'Discussion' oriented, so I'll try to stay away from that approach, and focus more on relating the science with supporting evidence. Even some journal articles are organised that way, and I feel like it's been pounded into me by years of courses. Time to move on. Great advice! 

And I'll switch up the presentation to focus more on the science stories I'm likely to tell, how, and their importance. 

Note that I'm TAing until just before our meeting this afternoon, so there won't be any more updates by then.

**Comment by kurtisanstey** [comment]
![image](https://user-images.githubusercontent.com/57200139/109340673-2c266d80-781e-11eb-9a5d-3626fc0887b1.png)
![image](https://user-images.githubusercontent.com/57200139/109340562-07ca9100-781e-11eb-9862-4b747b0d00d8.png)
![image](https://user-images.githubusercontent.com/57200139/109340743-3fd1d400-781e-11eb-8edf-820f464784a2.png)
![image](https://user-images.githubusercontent.com/57200139/109340790-511ae080-781e-11eb-9a74-33c8a5e78127.png)

**Comment by kurtisanstey** [comment]
![image](https://user-images.githubusercontent.com/57200139/109344270-575f8b80-7823-11eb-92bb-dba958cd55d5.png)

**Comment by kurtisanstey** [comment]
Meeting notes:

- Check N dependence on depth. Shouldn't be using an average value for each depth.
- fM2 is mostly M2 near Upper Slope bottom, which is surprising.
- Check rotation for inertial band.
- Check backscatter data for increased high-freq in cross-slope @ -99 m (interesting if real)
- Radius of f circle to see if it can make it into canyon
- Reduction of f at depth is possibly due to the nearby slope
- Check Axis data up to -450 m using depth/time frequency band integrals
- Use tidal analysis to separate the barotropic and baroclinic tides
- Blue shifts are necessary for f to propagate downward, as well as beta plane skewing of frequencies (Kundu)
- 2 MHz instrument at Axis, but has issues
- Get ADCP summary slides from Steve, showing mean current direction through depth
- Where do the currents transition from canyon to slope effects
- ONC Oceans 2.0 dive climatology (ROV/mobile platform) or Jody suggests Water Properties from La Perouse

**Comment by kurtisanstey** [comment]
Start with science
No text heavy slides
Explain plots first
