### ISSUE TITLE
Axis 55 kHz noise floor

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#19]
I get the following parameters from the device Additional Attributes https://data.oceannetworks.ca/DeviceListing?DeviceId=22925 and the NetCDF metadata:  

AverageInterval = 108
MAveragingInterval = 108
NumberPings = 6
adcp_setup_cell_size_meters = 20 (from metadata and agrees with depth intervals in data; differs from Additional Attributes which says 10 but with no record of any changes, this could be the problem - see end of comment)
SoundVelocity = 0
Salinity = 34
PowerLevel = -2

I use these values in the Nortek Signature 55 Deployment software (https://www.nortekgroup.com/software) to get the ping uncertainty (called horizontal precision). The noise floor should be somewhere around 4e-1, and I'm sure the PSD amplitudes are correct as they are similar for the other instruments, which have a confirmed noise floor.
___________________________
I start by assuming 1 ping every 18 s since that is the raw time interval, for which software gives an uncertainty of 3.82 cm/s. This is too low. 

![image](https://user-images.githubusercontent.com/57200139/107832875-71d73680-6d46-11eb-94cf-a439350f21a0.png)
___________________________
Then I try the ONC given parameters of 6 pings per 108 sec averaging interval, which still suggests 18s for a single ping. This is the same noise floor as the first case, and I don't understand how the time steps could be 18 s when all the intervals are listed as 108 s. And as the Nyquist frequency gets smaller for the 108 s interval it's even more off. This isn't right, either.

![image](https://user-images.githubusercontent.com/57200139/107835927-29247b00-6d50-11eb-9ecd-f06377847d53.png)
___________________________
So that's all wrong. However, the software says the lowest the pings can go is 6 s intervals, so maybe that's the case and ONC hasn't listed it properly. This gives a larger uncertainty from the software, at 6.62 cm/s, but it turns out it's just the same noise floor. **The 18 s uncertainty must just be averaged from the 6 s value**. This doesn't help, for either 18s or 108s averaging intervals.

![image](https://user-images.githubusercontent.com/57200139/107834468-19566800-6d4b-11eb-80c6-084efae9a999.png)
![image](https://user-images.githubusercontent.com/57200139/107834870-671fa000-6d4c-11eb-88bd-92557a8dba4e.png)

The noise floor is the same in every case - and too low.

**Comment by kurtisanstey** [comment]
Now, if somehow the depth cell size was 10m as is listed in the instrument attributes, not 20m like in the metadata, then the uncertainty from the software jumps up to 10.54 cm/s for pings averaged at 18 s...

![image](https://user-images.githubusercontent.com/57200139/107839498-21210700-6d61-11eb-8c34-55a782d692a8.png)
![image](https://user-images.githubusercontent.com/57200139/107836328-98e73580-6d51-11eb-8465-70eedd241d1d.png)

This noise floor is pretty spot on, and fits all of ONCs listed parameters except the depth cell size. I think this may be the problem, but the data _is_ in depth bins of 20 m... Maybe it's averaged somehow that the software doesn't account for? Otherwise, I'm at a loss and will send an email to ONC to see if they can clarify any of this.

Thoughts?

**Comment by kurtisanstey** [comment]
@jklymak I forgot to tag you. See above two comments, and below for what the noise floor used to look like (it was wrong, anyways).

Previous incorrect noise floor (too low):
![image](https://user-images.githubusercontent.com/57200139/107836409-e4014880-6d51-11eb-8286-bb9d240b32e5.png)

**Comment by jklymak** [comment]
@kurtisanstey why do you keep changing `dx`? That is a given in the data, and it is not a mystery.  The data is collected at some rate dt apart, that you get from the *data set* not from anything written down.  fN = 1/(2* dt).  

A single ping has a standard deviation that you get from the manufacturer, `std`

ONC averages a certain number of pings for each data point they give you.  Lets call that npings.

The white noise level is: 

```
phi = std**2 / (npings * fN)  # m^2/s^2 Hz^{-1}
```

The only thing that should be tricky is figuring out npings.

**Comment by kurtisanstey** [comment]
@jklymak 

I agree with you, and I do know what the dt and fN of the raw data is, they're 18s and 2.77e-2. And based on the software, I believe there are three 6 s pings for every 18 s interval, where 18 s is also the raw sampling rate (dt), giving a Nyquist frequency (dx) of 2.77e-2. I've updated my plots above with the proper fN and std (it gives the same better noise floor of 0.4 because the ping uncertainty was just averaged for 108s, before), and I still believe that part of the problem may lie in the depth bin size.
_________________________

The reason I was changing fN around earlier was to see if something fishy is happening, and there is. The raw PSD just didn't look right, even with what I knew were the correct fs and fN. Turns out the sampling rate _is_ every 18s as it should be, but somehow every 6th entry is 270s from the previous one (a gap of 15 samples). This is consistent throughout this raw dataset for the 55 kHz instrument, but was not the case for the 75 kHz instruments:
![image](https://user-images.githubusercontent.com/57200139/107838278-0303d880-6d5a-11eb-8c2e-cf9d326d3aa6.png)
![image](https://user-images.githubusercontent.com/57200139/107839361-3a758380-6d60-11eb-9a9e-fd8e8b782e69.png)

This is a new issue that I need to check for in some other raw samples for this instrument, and then let ONC know (because I assume it will be averaged into the 15-minute data).

**Comment by jklymak** [comment]
Every 5 minutes they get 6 pings?   So 15 minutes would be 18 pings.

**Comment by kurtisanstey** [comment]
@jklymak 

Geez, I think you figured it out. I thought something was wrong with the sampling. Is this a common way of recording ADCP data, in pulses of pings with a break between? My inexperience with these instruments is showing.

![image](https://user-images.githubusercontent.com/57200139/107859316-91756a00-6ded-11eb-923a-b677214d380b.png)
![image](https://user-images.githubusercontent.com/57200139/107859326-9b976880-6ded-11eb-835c-d9cffb2cac8e.png)

**Comment by kurtisanstey** [comment]
- [x] Try with 15 pings per 900 s (on average). 
- [x] Discuss with ONC re ping averaging, cell size vs depth size, etc.

**Comment by kurtisanstey** [comment]
Email sent to ONC for parameter and ping averaging confirmation. Plots for the 15 pings per 900s (on average) look very close.

![image](https://user-images.githubusercontent.com/57200139/108797578-54714c00-7540-11eb-8bf0-88dd07732e8f.png)

**Comment by jklymak** [comment]
Seems good.  The real noise floor could also be a touch out of spec because of poor scatterers.

**Comment by kurtisanstey** [comment]
When ONC follow up, suggest that they don't do pulses going forward, or change the data averaging to 18-minutes.
