### ISSUE TITLE
Finish Proposal

### ISSUE THREAD

**Issue by jklymak** [kurtisanstey/project#2]
- a bit more on internal wave continuum...

**Comment by jklymak** [comment]
OK< the scope of the "Project Goals" is good, and the organization seems good.  The writing though!  

1. Go ahead and use active voice for things you are actually going to do.
2. Only use adjectives when they are needed.
  - "Temporally, this can be compared to the observed seasonal forcing by the wind and mean currents, and regular tidal cycles, to reinforce their correlation." would read more cogently as: "We will compare the spectra to forcing by the wind, mean currents, and tide".  If you want to add something about timescales you could tack on " at time scales ranging from decadal, through seasonal." 

There were lots of instances earlier of too many adjectives or adverbs.  Suggest you take a quick pass through and check if every adjective is necessary and cut those that don't add to the sentence.

**Comment by kurtisanstey** [comment]
Great feedback, I'm on it!

**Comment by kurtisanstey** [comment]
I believe I've addressed your feedback! Here it is:
https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Proposal_Draft.pdf

Let me know if this is OK, and I'll draft a message to Steve and Rick.

**Comment by kurtisanstey** [comment]
Hi @jklymak , no pressure at all, but if you have a moment to look at the proposal draft in my previous post I can try to make any necessary changes before our meeting, or draft up an email to Rick and Steve if it's OK. If you're busy, don't worry about it!

**Comment by jklymak** [comment]
Thanks for the reminder Kurtis.  Yes, please send to them.  Thanks and nice progress!  Cheers,   Jody

**Comment by kurtisanstey** [comment]
Thanks, Jody! Will do.

**Comment by kurtisanstey** [comment]
Sent to Rick and Steve for review.
