### ISSUE TITLE
K1 summary

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#21]
Characterise the features of K1

**Comment by jklymak** [comment]
Now that you have time-frequency matrices saved (right), I think you should make time-depth-frequency matrices.  i.e. `phi_cw[ndepths, ntimes, nfreqs]` and `phi_ccw` the same size.  Then notching out frequencies or depths is easy.

**Comment by kurtisanstey** [comment]
@jklymak first step, save the time-frequency matrices. I'll get right on it.

**Comment by kurtisanstey** [comment]
*Jody, this is just for rough work.*
Need to check K1 strength through depth and time.

**Annual observations**:

**Upper Slope -99 m:**
- On the edge of the upper layer K1 is one of three primary frequency constituents, along with f and M2.  
- K1 is strongest in the cross-slope direction (~3e2 (m/s)^2/Hz); about equivalent to M2, and less than f.
- K1 is weaker in the along-slope direction (~1e2 (m/s)^2/Hz); less than both f and M2. 
- In both directions the K1 peaks are of similar shape.
- Changes between years are subtle.
- Obviously stronger in the CW rotary direction; similar features to the cross-slope peak (but slightly greater).
- Weaker in the CCW rotary direction; similar features to the along-slope peak (but slightly weaker), and no f.
- Spectrograms indicate spring/summer intensification of the K1 signal, at this depth, mostly in the cross-slope direction.

**Upper Slope -355 m:**
- Near the shelf floor, about 50 MAB, the K1 signal shows nearly identical features to the -99 m constituent, but with the directions swapped - along-slope is now stronger. Note: f is nearly gone, while M2 is stronger, at this depth.
- Rotary directions also swap compared to -99 m - CCW is now stronger, but CW and CCW are also closer together, suggesting more rectilinear motion at this depth. 
- Spectrograms indicate spring/summer intensification of the K1 signal, at this depth, mostly in the along-slope direction.

**Axis -696 m:**
- Mid-depth within Barkley Canyon, K1 shows a significant reduction compared to Upper Slope (lowest of all depths analysed).
- The peak is not well-defined, but shows somewhat higher variance (wider and taller) in the cross-slope direction (only ~3e1 (m/s)^2/Hz); somewhat weaker than f (amplified in canyon?), and much weaker than M2.
- K1 is somewhat weaker in the along-slope direction (~1e1 (m/s)^2/Hz); much weaker than M2, but equivalent or greater than f.
- Changes between years are subtle.
- Rotary motions are nearly rectilinear at this depth, and of similar magnitude to the PSD; somewhat weaker than f (amplified in the canyon even in CCW?), and much weaker than M2.
- Spectrograms show very weak K1, with weak seasonality (slight increase in summer).

**Axis -904 m:**
- Near the canyon floor (about 100 MAB), K1 is the strongest of all analysed depths.
- K1 is strongest in the along-slope direction (~1e3 (m/s)^2/Hz); stronger than f, and nearly comparable to M2.
- K1 is weaker in the cross-slope direction (~6e2 (m/s)^2/Hz); stronger than f, but less than M2.
- In both directions the peaks are of similar shape.
- Changes between years are subtle.
- Rotary motions are rectilinear at this depth, and of similar magnitude to the PSD (between the two directions); stronger than f, but less than M2.
- Spectrograms indicate spring/summer intensification of the K1 signal, at this depth, mostly in the along-slope direction. 

**Potential stories**: 
- Spring/summer intensification of the K1 signal could be related to the seasonal switch to upwelling favourable winds from the NW, which leads to deep up-canyon flow and possible enhanced generation of diurnal shelf waves at the mouth of the Strait of Juan de Fuca. K1 is sub-inertial at this latitude, so should be largely barotropic unless there are baroclinic contributions that are remotely generated (e.g. Juan de Fuca CTW, or internal tides from 'nearby' irregular topography such as the Endeavor portion of the Juan de Fuca Ridge, etc.) or generated within the canyon (near-bottom?).
- Upper layer cross-slope K1 signal stronger due to propagation of barotropic tide?
- Near shelf along-slope K1 signal stronger due to the influence of the strong regional NW/SE mean currents at this depth, and/or contributions from baroclinic diurnal shelf waves from Juan de Fuca mouth.
- K1 is reduced below the canyon rim, but may be beginning to the show the effects of canyon steering.
- There could be some near-bottom canyon amplification (and flow steering) of the baroclinic K1 signal.

**Comment by kurtisanstey** [comment]
Rough work on the diurnal write-up. Plots are being updated to reflect the stratification dependence, which is essential to determining the validity of many of these arguments.

**This paragraph should be expanded to further discuss canyon steering**
**Include plot of cross- and along-slope diurnal depth/band power for both sites**
**Maybe a rotary plot of the same, showing convergence with depth**
**Maybe do these through time (2-week or monthly bins)**
**Maybe flow direction vs depth overlaid on topography (consider different coordinate systems between sites)**
The diurnal signal is one of the dominant frequency constituents in observed spectra, at both sites. There is a notable switch in dominant direction from cross-slope near the surface, to along-slope near the shelf. The upper layer cross-slope dominance could be incident barotropic tides, while the lower layer may show the effects of the shelf on regional coastally trapped waves of diurnal frequency (CTW). At this latitude, the diurnal constituent (approximately 1.15e-5 Hz) is sub-inertial (the local Coriolis frequency, _f_, being approximately 1.73e-5 Hz), and so lies outside of the bandwidth for free internal waves, which exist within the frequency boundaries of _f_ and _N_, _N_ being the stratification dependent Brunt–Väisälä or buoyancy frequency. It is expected that the local signal should be largely barotropic unless there are significant sources of forced baroclinic diurnal activity nearby. In fact, there are CTW of diurnal frequency being generated at the mouth of the nearby Strait of Juan de Fuca, which propagate poleward along the Vancouver Island Continental Shelf (Cummins et al., 2000). CTW are depth- and boundary-dependent, and travel with signature vertical structure and speed, while barotropic tides are essentially linear in the vertical. Therefore, evidence of vertical structure in the diurnal band could indicate the presence of regional CTW incident with canyon topography. The rotation of the diurnal signal to along-slope at depth for the Upper Slope ADCP may suggest that the signal contains incident CTW which would travel along the shelf as an external boundary. It is possible that the directional depth dependence could also be influenced by the strong regional mean currents below the upper layer, primarily being the California Undercurrent and the spring/summer shelf-break current, which run NW and SE in the along-slope direction (Thomson and Krassovski, 2015). In-canyon, the diurnal signal shows steering effects and appears to follow the topography as it changes with depth. Rotary analysis shows a strong CW dependence near the surface that becomes progressively rectilinear with depth, as f decreases due to the steep canyon walls (Kunze et al., 2002) and the possible effects of canyon steering take hold.

**This paragraph needs to be revised when appropriate stratification scaling has been applied**
**Include plot of diurnal spectrogram, seasonal wind patterns**
There is consistent seasonal variability in the diurnal band, with spring and summer intensification possibly related to the seasonal switch to upwelling favourable winds from the NW (Thomson and Krassovski, 2015). These seasonal wind patterns may also effect the generation of CTW from the Juan de Fuca, and so a baroclinic signal would likely be effected (Cummins et al., 2000). This is observed at all depths, though the effects are most noticeable where the diurnal signal is strongest; the upper layer and lower canyon. The upper layer likely has increased variance due to the high stratification near the surface, which will be adjusted for with depth-dependent scaling based on local buoyancy profiles. The lower canyon may be showing increased variance due to the effects of topography focused rectilinear flow near the canyon floor, as the Axis ADCP is located at a narrow bend where up-canyon velocities should increase; internal wave fluctuations in canyons have been noted to increase by up to a factor of 10 near the canyon floor (Kunze et al., 2002).

**Comment by kurtisanstey** [comment]
**Update** 

Characterise the features of K1:
- [x] Apply WKB stretch
- [x] Outline of observations
- [x] Rework code to rely on saving and loading at each major step
- [x] Create time-depth-frequency matrices 
- [x] Time vs depth plots for power
- [x] Rotary versions
- [ ] Stats for significance (variance histogram/depth)
- [x] Different coordinate systems between sites
- [x] Direction vs depth
- [x] Seasonal wind patterns
- [ ] Include any science questions that come up along the way (in-progress)
- [ ] Do a proper write-up of results (in-progress)

**Comment by kurtisanstey** [comment]
@jklymak 

Do you have any suggestions for 3D plotting?

I tried adjusting pcolormesh vmin/vmax and it's very difficult to see any trends.

![image](https://user-images.githubusercontent.com/57200139/113326361-67f59c80-92ce-11eb-8d45-e46034d3f2ff.png)

So instead I've been battling with the mplot3d figures, which are very cool, but still somewhat difficult to pick out what's going on (ignore the wonky labels):

![image](https://user-images.githubusercontent.com/57200139/113330515-ac376b80-92d3-11eb-8117-a1ef709a9d15.png)

**Comment by jklymak** [comment]
I prefer the top plot.  Its exactly the right idea.  That there is no trend is still a finding!

**Comment by kurtisanstey** [comment]
@jklymak 

A few updates to add to my write-up (in more detail):

- At Upper Slope there is a general pulse of diurnal activity in the cross-slope direction during the late-spring/summer, associated with enhanced CTW generation due to the seasonal change in wind > currents (Thomson et al. 2007; Kuroda et al. 2017).
- Furthermore, a stronger cross-slope diurnal signal is expected above canyons along the shelf (Thomson et al. 1997).
- There is near-bottom intensification of the diurnal signal in the along-slope direction, associated with the deep cyclonic propagation of the diurnal tide in the north-Pacific basin interacting with the shelf edge (Cummins et al. 2000).

![image](https://user-images.githubusercontent.com/57200139/113346356-984a3480-92e8-11eb-9d59-0f88931cb34a.png)

- At Axis the upper canyon sees diurnal power of about the same magnitude as the Upper Slope average, with little structure through depth, expected as the canyon widens (Kunze et al. 2002).
- Near the canyon floor there is amplification of the diurnal signal to about 10x what is found in the upper canyon and at Upper Slope, due to topographically forced rectilinear flow (Kunze et al. 2002). 
- There is a lower-depth pulse of energy in the late-spring/summer associated with increased near-bottom up-canyon currents due to the switch to upwelling favourable winds at that time (Thomson et al. 2007).

(Note: Axis data still to be rotated to better reflect 'along-canyon' and 'cross-canyon')
![image](https://user-images.githubusercontent.com/57200139/113347954-cc265980-92ea-11eb-8e6e-e82d2b2a6fbd.png)

**Comment by kurtisanstey** [comment]
From #24 

https://github.com/kurtisanstey/project/blob/master/plots/depthband_plots/Diurnal_rot_Slope_2013.pdf
https://github.com/kurtisanstey/project/blob/master/plots/depthband_plots/Diurnal_rot_Axis75_2013.pdf

- At Upper Slope, diurnal currents above -250 m are mostly in the CW direction, as expected over the shelf (Cummins et al., 2000; Kuroda et al., 2018). 
- Closer to the bottom, there appear to pulses of CCW diurnal activity in both the late-spring/summer and late-fall/early-winter. 
- The CCW direction is odd, and it seems like it's connected to the switch from cross-slope (upper-depths) to along-slope (near the bottom) in the Cartesian PSD depth-band plots, which happens around the same depth. The deep along-slope currents are associated with the cyclonic propagation of the barotropic diurnal tide in the north-Pacific basin, which would be CCW in rotation (Cummins et al., 2000); furthermore, this tide rubbing against the shelf could generate upward (CCW), evanescent internal waves of diurnal frequency. 
- The spring/summer pulse is possibly correlated with the annual switch to upwelling favourable winds that increases CTW generation (Thomson et al., 2007). **But if the lower signal is CCW barotropic, why would it be affected?** NOT barotropic, or should be visible throughout the water column; see end of previous point for likely explanation.
- The winter pulse could be correlated to stormy weather (Thomson et al., 2007).
- At Axis, the CW and CCW depth-band plots are very similar, indicating fairly rectilinear flow in the deep canyon, as expected (Kunze et al., 2002). 
- Furthermore, near-bottom canyon intensification is present (Kunze et al., 2002). Vertical scales are clear, and will be identified.
- The same two pulses as above show up in the deep canyon, as well as apparent spring-neap effects.

**Comment by kurtisanstey** [comment]
@jklymak 

Read this whenever you get the chance, no rush (I've got plenty of other work to do!).

It's a good start (I think) to my diurnal write-up. It's obviously rough, and in much need of expansion and organisation; you'll see some of my notes as you go along (at the end of each paragraph). Asterisks show conjecture and require further research and/or a reference. For now, I'm just hoping you can see where I'm trying to go with each point, and perhaps offer some suggestions that aren't already highlighted.

https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Diurnal.pdf

**Comment by kurtisanstey** [comment]
From email:

1) figures: way too large and hard to read as a PDF form.  Part of this exercise is to get you to turn these into publishable figures.  These look *good* but they are far from publishable.  The fonts are too small on the spectra.  There is no need for the spectra to be so large, and you could easily fit four subpanels on half a page.  You still have all the lines as a legend whereas almost none of them need to be labeled via the legend. 

2) Writing:  have you picked an observational paper to base your writing style off of.  I think some of the text you wrote in the paragraphs were good, but one sentence saying something about the observation followed by 5 sentences of possible explanation is probably not good style.  Now that you have tried this yourself once, suggest you dig out a few good papers and read how they do it.  In particular you need to separate the incontrovertible from your interpretations, which may be more open to challenge. 

Overall for the section, what is your point?  What are the one or two things you think are very remarkable, and what agree with previous observations?  What are your conclusions? 

- [x] Send Jody **outline** on Monday (describe > compare (what) > explain (why)).
- [x] Note a few papers with good structure, to emulate.

**Comment by kurtisanstey** [comment]
**Papers with good structure** (to emulate):

- Alford, M. H., Mackinnon, J. A., Zhao, Z., Pinkel, R., Klymak, J., Peacock, T., … Peacock, T. (2007). Internal waves across the Pacific. Geophys. Res. Lett, 34, 24601. https://doi.org/10.1029/2007GL031566
- Cuypers, Y., Bouruet-Aubertot, P., Vialard, J., & McPhaden, M. J. (2017). Focusing of internal tides by near-inertial waves. Geophysical Research Letters, 44(5), 2398–2406. https://doi.org/10.1002/2017GL072625
- Martini, K. I., Alford, M. H., Kunze, E., Kelly, S. M., & Nash, J. D. (2013). Internal bores and breaking internal tides on the Oregon continental slope. In Journal of Physical Oceanography (Vol. 43). https://doi.org/10.1175/JPO-D-12-030.1
- Alberty, M. S., Billheimer, S., Hamann, M. M., Ou, C. Y., Tamsitt, V., Lucas, A. J., & Alford, M. H. (2017). A reflecting, steepening, and breaking internal tide in a submarine canyon. Journal of Geophysical Research: Oceans, 122(8), 6872–6882. https://doi.org/10.1002/2016JC012583

______________________________________________

- Notable effects: Apparent blue-shift. Near-shelf intensification. Canyon-axis intensification. Seasonality. 

**Diurnal outline**

**Upper Slope - Near-shelf intensification**

Describe (_what do I see_):
- Depth-averaged / multi-annual time-averaged PSD comparison to f and M2 (K1 < f < M2, shape of peak, etc.).
- Apparent blue-shift in spectral peak.
- Most of depth cross-slope and CW, as expected for diurnal signals over a shelf in northern hemisphere.
- Below -250 m intensification in along-slope, CCW signal, of about 1.5x orders of magnitude, to overtake cross-slope / CW signal.
- Vertical scale of effect approximately 150 m AB.
- Seasonality evident in late-spring / summer, and somewhat through the winter, possibly correlating with seasonal wind / mean-current shifts, and winter storms (weather data).
- Spring-neap modulates the effects, evident in barotropic time series (compare local vs remote forcing).
- _Be sure these are all quantified and related in clear figures._

Compare (_what did others see_):
- Allen, 1976.
- Thomson & Crawford, 1982.
- Chapman, 1983.
- Crawford & Thomson, 1984.
- Crawford, 1984.
- Hotchkiss & Wunsch (1982) found evidence of up to a 10x increase along-slope near to Hudson Canyon, and a vertical scale for the effect of about 150 m AB around -400 m depth. Correlation to direction and strength of both prevailing winds and mean currents, and storm events.
- Flather, 1988.
- Brink, 1991.
- Drakopoulos & Marsden, 1993.
- Foreman & Thomson, 1997.
- Polzin et al. (1997) found an increase of about 15x up to about 150 m over slope topography.
- Cummins et al., 2001.
- Jayne & St. Laurent, 2001.
- Nash et al. (2004) found similar effects at the Mid-Atlantic Bight slope off of Virginia.
- Kelly et al., 2010.
- Klymak et al., 2011.
- Klymak et al., 2012.
- Kunze et al. (2012) found similar effects at the slope near Monterey and Soquel canyons.
- Klymak et al., 2013.
- Martini et al., 2013.
- Johnston & Rudnick, 2014.
- Terker et al., 2014.
- Gemmrich & Klymak, 2015.
- Robertson et al., 2017.
- _Quantify (compare) where possible._
- _Find additional sources._

Explain (what may be causing this):
- Evanescent (diurnal is sub-inertial) internal tides locally generated from reflected cyclonic diurnal barotropic tides incident with the subcritical upper-slope (radiate upwards) (Hotchiss & Wunsch, Polzin, Kunze, Cummins). 
- Internal tides locally enhanced due to increased stratification effects near areas of high 'topographic relief', such as the shelf-break and slopes. These highly stratified turbulent layers experience the effects of reflection/scattering and internal tide and lee-wave generation.
- Poleward diurnal CTW from Juan de Fuca may induce similar effects (along-slope diurnal forcing over slope topography).
- _Discuss strengths and weaknesses of each theory._

**Axis - Canyon-axis intensification**

Describe (what do I see):
- Depth-averaged / multi-annual time-averaged PSD comparison to f and M2 (f < K1 < M2).
- Apparent blue-shift in spectral peak.
- Mostly along-canyon, rectilinear, as expected for canyon-guided flow.
- Below -750 m intensification in along-canyon, CW and CCW signal, of about 1.5x orders of magnitude (similar to Upper Slope).
- Vertical scale of effect approximately 250 m AB.
- Seasonality evident in late-spring/summer, and somewhat through the winter, correlating with seasonal wind and current shifts, and winter storms (similar to Upper Slope; show weather data).
- Spring-neap modulates the effects, evident in barotropic time series (similar to Upper Slope; compare local vs remote forcing).
- _Be sure these are all quantified and related in clear figures._

Compare (what did others see):
- Hotchkiss & Wunsch (1982) also found evidence of increased internal tides within Hudson Canyon, with a vertical scale for the effect of about 250 m AB around -800 m depth. Correlation to direction and strength of both prevailing winds and mean currents, as they affect upwelling which drives along-canyon currents. Only very strong storm events evident.
- Petruncio et al., 1998.
- Carter & Gregg (2002) observed a 200-300 m thick intensified bottom layer along the axis of Monterey Canyon.
- Xu & Noble, 2009.
- Kunze et al. (2002, 2012) found similar effects within both Monterey Canyon and Soquel Canyon, with intensification of over an order of magnitude at a vertical scale approximate 200 - 300 m AB near to -1000 m depth.
- Wain et al., 2013.
- Alberty et al., 2017.
- Kampf, 2018.
- Hamann & Alford, 2020.
- _Quantify (compare) where possible._
- _Find additional sources._

Explain (what may be causing this):
- Evanescent (diurnal is sub-inertial) internal tides locally generated from barotropic tides incident with the irregular canyon topography (floor/slope and wall features). 
- Topographically increased stratification (as for Upper Slope) amplifying the local internal tide.
- Poleward diurnal CTW from Juan de Fuca descending into the canyon and incident with the subcritical axis slope and supercritical canyon walls. 
- _Discuss strengths and weaknesses of each theory._

**Comment by jklymak** [comment]
The above looks like a great start Kurtis!  I like that the organization is parallel in each that will make those paragraphs easier to read.  May relate spring-neap to local versus remote (unmatched time) forcing.  

For the theories, I'm still not sure *how* they decided these theories make sense.  Are they wild speculations?  Numerical simulations?  Arrays of data?

**Comment by kurtisanstey** [comment]
Hi Jody.  A very useful exercise, for organisation. I'll do one of these for each section, as I go, like you suggested.

As for the theories, it varies; mostly informed speculation and comparison with numerical simulations. I've been focused on the Describe and Compare parts, so I'll have more details on 'how' for Explain this week.

**Comment by jklymak** [comment]
I agree with your focus on the Describe and Compare.  The "How" will likely be in the discussion anyways.

**Comment by kurtisanstey** [comment]
Reorganised into new issues (this will be kept for specific reference).
