### ISSUE TITLE
Rotary spectra

### ISSUE THREAD

**Issue by jklymak** [kurtisanstey/project#3]
Rotational spectra need to have Welch's method applied to them.   Get them to work for time-domain

- check versus toy model and hard-wired code.

- 2-D rotational spectra.  Get to work in t-z domain...

**Comment by kurtisanstey** [comment]
Update from email:

The rotary averaging is working! I got it, yesterday, so I'm still working on a full set of plots, but I've attached a few samples. Normalisation checks out. If interested, you can check the working code in the rotary_test.ipynb notebook for a comparison between the previous non-averaged and new averaged process, and in the Rotary section of the analysis.ipynb notebook for application. I reread some papers that make use of rotary spectral analysis, and mine looks appropriate. As you can see in rot_slope_2013.png, the inertial constituent is gone from the CCW spectrum, and CW motion dominates, with similar notable frequencies as in the PSD (K1, f, M2, fM2, M4, etc.). Added to the To Do list: make all rotary plots for important comparison seasons/years, compare inertial strength with seasonal wind forcing, filter barotropic tides and see what's left for baroclinic tides.

Question: With rotary spectra being piecewise PSD plots that provide more information, are PSD plots necessary at all?

![rot_test_no_avg](https://user-images.githubusercontent.com/57200139/97617420-fb9f0600-19da-11eb-8fdd-881b3f281b16.png)
![rot_test_avg](https://user-images.githubusercontent.com/57200139/97617412-f80b7f00-19da-11eb-81e9-2e922e1fd6a1.png)
![rot_slope_2013](https://user-images.githubusercontent.com/57200139/97617398-f3df6180-19da-11eb-8fb1-8f1861a2aa9e.png)

**Comment by jklymak** [comment]
WRT your question - they are redundant.  I'm not sure I have a way to do the Garrett and Munk CW/CCW components, but it should be possible.

**Comment by jklymak** [comment]
- why CCW M_2 smaller than CW M_2?
  - K1 
  - consistency relations for ratio of CW/CCW?
  - roll off at frequencies higher than M4...
- Garrett and Munk? CW/CCW spectrum?

**Comment by jklymak** [comment]
- spectrograms?

**Comment by jklymak** [comment]
- with/without the vertical mean?

**Comment by kurtisanstey** [comment]
- [x] Find consistency relations for ratio of CW/CCW (Gill; Klymak, 2015). It's CW/CCW = ((w+f)/(w-f))^2
- [x] Find out if there is already, or some way to obtain, a rotary form of the GM spectrum. See Kunze & Gregg ~1991, and GM issue for more details. Use the current rotary GM process to begin analysing rotary plots.
- [x] Update notable seasonal and annual plots with rotary spectra, in Analysis document.
- [ ] Create spectrograms using rotary spectra, to highlight seasonal changes in inertial band.
- [ ] Check if there is a characteristic rollout for frequencies above M4.
- [x] Determine instrument noise floor.
- [x] Recheck normalisation vs PSD.
- [ ] Try spectra with and without the vertical mean to compare barotropic and baroclinic signals.
- [ ] Create 2D rotary spectra, once 1D are optimal.

**Comment by kurtisanstey** [comment]
@jklymak 

Rotary spectra plots are up! I'm currently in the process of updating the Analysis document with detailed analyses, but here is a general summary: 

- Overall, variance is comparable for both Slope depths (except 2010), and greater nearest to the bottom for the Axis depths.
- 2010 seems to be an outlier year for many reasons, so I will recheck the data quality to see if there are any issues.
- The Axis 55 kHz spectra are all similarly shaped, but different from the 75 kHz instrument. The Axis 55 kHz instrument has a much more prominent 'flattening' at high frequencies, compared to the 75 kHz instrument. As the 75 kHz instrument is only currently being used for 2013, analysis will (for now) be only for the 55 kHz years (2017, 2018, 2019).
- As expected for the Northern hemisphere there is generally more variance in the CW direction than CCW, though the difference becomes less with depth. By -900m, there is little difference in the primary tidal and near-inertial constituents.
- CCW shows a significant reduction in the inertial/near-inertial band, particularly at upper depths where this band is more prominent.
- K1 is greater in CW near the surface, and CCW deeper. 
- K1 peak has similar variance for all Axis years, and is quite broad.
- M2 is generally greater in CW.
- M2 peak has similar variance for all Axis years, and is about half the width of the K1 peak.
- M2 and M4 are possibly evident at all depths.
- In most cases, the roll-off higher than M4 exceeds the GM model.

Here are some samples:
https://github.com/kurtisanstey/project/blob/master/plots/rot_plots/rot_Axis55_2017.pdf
https://github.com/kurtisanstey/project/blob/master/plots/rot_plots/rot_Slope_2017.pdf

**Comment by kurtisanstey** [comment]
Analysis document updated with sample rotary spectra and observations.

**Comment by kurtisanstey** [comment]
- [x] Find consistency relations for ratio of CW/CCW (Gill; Klymak, 2015). It's CW/CCW = ((w+f)/(w-f))^2
- [x] Find out if there is already, or some way to obtain, a rotary form of the GM spectrum. See Kunze & Gregg ~1991, and GM issue for more details. Use the current rotary GM process to begin analysing rotary plots.
- [x] Update notable seasonal and annual plots with rotary spectra, in Analysis document.
- [x] Determine instrument noise floor.
- [x] Recheck normalisation vs PSD.
- [ ] Create spectrograms using rotary spectra, to highlight seasonal changes in inertial band.
- [ ] Check if there is a characteristic rollout for frequencies above M4.
- [ ] Try spectra with and without the vertical mean to compare barotropic and baroclinic signals.
- [ ] Create 2D rotary spectra, once 1D are optimal.

**Comment by kurtisanstey** [comment]
Remaining rotary spectral analyses will be included in upcoming write-ups.
