### ISSUE TITLE
Critical slope analysis

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#39]
- Critical slope angles (beta) for both Upper Slope and Axis were determined from 3 km E-W and N-S cross-sections of bathymetry, respectively, centred about the ADCP, from rise-over-run estimations. 
- Incident internal wave and tide angles determined for major constituents as alpha = sqrt[ (omega^2 - f^2) / (N^2 - omega^2) ], making use of N_0 from WKB scaling.
- Upper Slope is supercritical (beta > alpha) to the semidiurnal tide (alpha_M2 ~ 0.037), at beta ~ 0.060, so there should be reflection (M2 is CW/downward in the slope intensification layer, so this could be). 
- Axis is subcritical (beta < alpha) to all observable free internal waves and tides as beta ~ 0.019 (alpha_f ~ 0.023). 
- This is about critical for near-inertial waves, so there could be canyon floor amplification of the near-inertial band (there appears to be). 
- Both sites are in the 'near-critical' zone where beta / alpha ~ 1, where despite some reflection or scattering there should also be significant near-topography intensification (as is observed).
- Created new topography map for each site to show relative location to local features (slope and canyon).
- Updated bathymetry to show 3 km cross-section lines (red dashed).

**Comment by jklymak** [comment]
This looks good.  Also suggest just calculating the 2-d gradient and doing the same calc, but with the absolute value of the gradient.

**Comment by kurtisanstey** [comment]
- [x] Add ray tracing graphic to topography plot, for semidiurnal.

**Comment by kurtisanstey** [comment]
- [x] Ray tracing (accounting for stratification; see paper Jody linked).

![image](https://user-images.githubusercontent.com/57200139/126435804-bafddebd-3c90-4757-941e-eac97741b80f.png)

- [x] Get gradient at each grid point for bathymetry, plot M2 criticality.

**Comment by kurtisanstey** [comment]
- Calculated the gradient magnitude (slope, beta) at each grid point.
- Divided by alpha_M2, adjusted for the depth at each grid point from elevation data.
- Near-critical is white, subcritical is blue, and supercritical is red.
- Most of the region is supercritical to M2, with notable exceptions at the canyon bottom and above the shelf-break. 
- Upper Slope instrument site is on the supercritical edge of the near-critical region below the shelf-break; mainly downward reflection.
- Axis instrument sits on the subcritical canyon floor surrounded by the supercritical canyon walls; upward reflection at the canyon floor and downward reflection from the canyon walls, together could lead to M2 internal tides 'trapped' in the lower canyon?

![image](https://user-images.githubusercontent.com/57200139/127244623-f392498e-8fb4-4e50-a4ae-c2856e6bf63e.png)

**Comment by kurtisanstey** [comment]
- [x] Put the depth contours on this plot, rather than the topography.

![image](https://user-images.githubusercontent.com/57200139/127752814-d72991ec-637e-435c-bac8-84ec6c839db9.png)

Will use this as primary site plot and for criticality discussion.

**Comment by kurtisanstey** [comment]
- [x] Desaturate red a bit.
- [x] A few major contours (200,500,1000,1500?) thicker, the rest thinner.
![image](https://user-images.githubusercontent.com/57200139/128782028-85e4ad6f-8b29-4521-84f2-74ec823e9dc0.png)

**Comment by kurtisanstey** [comment]
Done for now! Can revisit if need to change anything for publication. Using as site map and in criticality writing.

Update: Removed labels from sub-contours.
