### ISSUE TITLE
Continuum fits

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#40]
- Power law fits were manually plotted for PSD spectra as Ax^(-k).
- The first range of frequencies, the 'continuum', is also the new range for the depth-band integrated power analysis, from 7e-5 Hz to 1.6e-4 Hz, which is greater than M4 to about 1/2*N. This frequency range characterises adherence to the GM -2 slope.
- The second range of frequencies, the 'roll-off', characterises the spectral roll-off, emphasising energy transfer from low- to high-frequency processes. It ranges from 1.7e-4 Hz to 4.0e-4 Hz, approximately 1/2*N to N.
- Samples are below (the rest are in the PSD plots folder, for reference). 
- Upper Slope continuum is close to the expected GM slope, ranging between -1.8 and -2, with the along-slope component often the shallower of the two. 
- Upper Slope roll-off is consistent at -1.5, except for -1.4 in 2018.
- Axis75 continuum is much shallower, at -1.7, likely heightened due to canyon effects.
- Axis75 roll-off varies between -0.8 and -0.7, again likely heightened due to canyon effects.
- Axis55 continuum is shallower again, ranging between -1.2 and -1.4.
- Axis55 roll-off varies between -0.3 and -0.4.
- I doubt that comparing the 55 kHz instrument with the two 75 kHz instruments is OK, as Axis55 has a much higher noise floor, and this seems to begin affecting the slope as early as the 'continuum' bandwidth.

**Comment by kurtisanstey** [comment]
- [x] Use np.polyfit to get better values for A and k.
- [x] Put these on the standard PSD plots, no need for new plots.
- [x] Don't use depth-mean PSD.
- [x] Add/remove plot fluff and important details (WKB scaling, units, depth-mean, long titles that aren't important, etc.).

**Comment by kurtisanstey** [comment]
- Used a SciPy power law fitting method to get the a and b values for each PSD, for a fit line of y = ax^b.
- Narrowed the range for the 'continuum' as 7e5 Hz (above the notable tidal harmonics) to 2e4 Hz (below both N and a notable whitening zone). This was applied to other analyses that use the 'continuum' range.
- This was done for the lowest depth evaluated for each instrument, and at mid-depths.
- Added fits to standard PSD for reference, rather than zoomed plots.
- Slopes amplified and steeper near the bottom (they don't need to 'flatten' to reach the high-frequency roll-off).
- [ ] Compare amplitudes and slopes to GM in this frequency range.

**Comment by jklymak** [comment]
OK - to get a time series you will need to fit `c f^-2`, which should be easier.  So I see two products:

- [x] A time series of a and b from `a f^b`
- [x] A  time series of c from `c f^-2` (shown as c/GM)

the first tells us how GM-like the spectrum is.  The second compares amplitude in a consistent way, where of course we need to be careful if b deviates substantially from -2.  

Kurtis' note: For the second one, multiply by f^2 (whiten) and take average over band.

- [x] Afterwards: estimate dissipation rates (epsilon, etc.).

**Comment by kurtisanstey** [comment]
**Rough notes:**

- Time series for a and b at each site, for each year. 
- Still working on time series of c.
- Values are obtained for each window in the spectrograms (~9 days, 50% overlap), at ~50 m AB.
- At this temporal resolution the variability of both a and b is very large (e.g. for b, from -5 to 0).

9-day windows:
![image](https://user-images.githubusercontent.com/57200139/124857188-14e45300-df69-11eb-89e2-e005ec18ac57.png)

- **Question for Jody:** I didn't expect the a and b time series to be so variable. Is ~9 days too short of a window to get a good estimate of the continuum? I thought so, so either the slope varies significantly or I'm wrong. I doubled nperseg (~18 days, 50% overlap) to get better frequency resolution (but worse temporal resolution, of course). Thoughts?

18-day windows:
![image](https://user-images.githubusercontent.com/57200139/124858544-82917e80-df6b-11eb-849d-a4b5e0cff1ec.png)
![image](https://user-images.githubusercontent.com/57200139/124859692-96d67b00-df6d-11eb-9e70-4a152f726292.png)

- When a is displayed with a log scale, a and b time series appear to have identical shape (positive correlation).
- There are no recurring seasonal features (similar to integrated continuum power).
- Pulses in integrated continuum power do not align with time series features.

**Comment by jklymak** [comment]
I'm not sure what the last plot is showing.  

a and b will be correlated, but that doesn't mean anything because if you increase the power law you need to decrease the amplitude.

Still suggest fitting c f^2  and plotting c.  b is useful info as well, but its hard to get an amplitude if it is changing.  We are looking for amplitude changes.

**Comment by kurtisanstey** [comment]
@jklymak the last plot is for visually comparing integrated continuum power features to what's seen in the a and b plots (they aren't similar).

I'm already in process working on the cf^-2 fits!

**Comment by kurtisanstey** [comment]
- [x] Time series of cf^-2. Compare w/ GM over time (could plot GM line, divide by GM, or take difference).
- [x] Do this for each depth to get depth-time-amplitude plots.

- At each window whitened the spectrum, and then took the average over the band. 
- Same method applied to GM (1/2 for components).
- After doing this at a single depth, I ran the process for all depths to get depth-time-amplitude.
- These were divided by the GM amplitude to produce the c/GM comparison plots, below.

- Cross-slope and cross-canyon generally stronger (as in spectra).
- Inter-annually trends are similar but amplitudes vary.
   - At Slope, lulls in summer (as in integrated continuum power plots). Over 3x GM (1/2) amplitude near topography.
   - At Axis, seasonality is less obvious. Over 5x GM (1/2) amplitude near topography; all depths somewhat elevated.
- Plots are very similar to the previous depth-band integrated power plots that I made for the continuum. When continuum power increases so does its amplitude vs GM. I would say this is an expected result.

All depths:
![image](https://user-images.githubusercontent.com/57200139/126411155-cdafabe6-4504-4d97-aed0-61edd29e7bdf.png)

Depth-band integrated power for comparison:
![image](https://user-images.githubusercontent.com/57200139/125852128-b03545c7-077c-4c66-bb45-74c911a1422c.png)

- [x] Get other years for the c/GM comparison.

**Comment by kurtisanstey** [comment]
- [ ] See #47. Redo c/GM with better time resolution, narrower bandwidth (6e-5 to 1e-4). Keep this one as components to show not GM-like (components differ).

Optional:
- [ ] Could try c without whitening, just fit -2 to get amplitude? I think the way I'm doing it is fine, as long as the process is the same.
- [ ] Fit -2 to Axis75 and Axis55 to show deviation if narrower bandwidth doesn't help.
   - [ ] Or even just whiten PSD to better show slope deviation.

**Comment by kurtisanstey** [comment]
Combined this with Dissipation Estimates, Issue #47.
