### ISSUE TITLE
Writing updates

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#46]
For notifying Jody of writing updates as the thesis progresses.

Access the rough thesis document from the readme, documents folder, or using the following link:
https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Thesis_Rough.pdf

**Comment by kurtisanstey** [comment]
@jklymak 

- I don't expect you to read the current version, as it's a bit messy, but **I would like to have a mostly fleshed-out draft to you for next week**.
- I'll be using this issue for notifying you of thesis updates for meetings, etc., as I won't be putting so much detail into the GitHub issues anymore. I'm trying to incorporate updates directly into the rough thesis document.
- For today, I've reworked the organisation of the thesis to better tell the stories, created point-form outlines for sections that have yet to be addressed, made general notes for figures to make, moved some of the Methods into the appropriate Results sections, removed or moved some of the more speculative statements to Discussion, and did some writing for almost every section of the document - it's on its way.
- [x] Point form with clear figures, to get going.
- [x] Include main points at the beginning of each section.
- [x] At the beginning of each write-up list the main points! They're not secrets.
- [x] Write a bit every day!
- [x] About 25 figures for thesis.
- [x] Focus on FIGURES for now! 'Point' form stories are fine.
- [x] Cross-correlate plots for big-picture story comparison; **_figures_** should tell the story!
  - [x] Cascade of energy from where to continuum (compare seasonality).
  - [x] Reduce total number of stories/plots to be concise!
- [x] Finish updating plots and expand on later sections.
- [x] Connections between main points!
- [x] Show inter-annual variability (comparative plots, same forcing means topography, etc.).
- [x] Put main plots in body of thesis.
- [x] Only mention speculation in Results, most should go in Discussion section. A subsection for each main point or band. Significant > speculation > additional analysis. Include ALL theories and possibilities, if more than one exists.
- [x] Either remove upper depths or put dashed line on plots to show analysis region.
- [x] Comparisons for along-canyon mean flow.
- [x] Plot band-pass ranges on PSD / rotary spectra.

**Comment by kurtisanstey** [comment]
@jklymak 

- Don't feel obligated to read any of these documents, it's all in-progress writing.
- Updates regarding potential generation sites for the barotropic timing offset noted in the semidiurnal band, each spring (I'll give you details, tomorrow). I'm trying to add all new work directly to write-ups with relevant figures, so here's the semidiurnal write-up (in-progress, just point-form observations at this point): https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Semidiurnal_Rough.pdf
- I'm reworking the entire thesis document with this approach, as we discussed, but I don't expect you to keep track of it while that's in progress. You can always access that document with the link at the top of this page, or in the readme. Chat tomorrow with more details! https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Thesis_Rough.pdf

**Comment by kurtisanstey** [comment]
**Summary:**
- Mean currents as expected. Topography guides flow (generally along-slope/canyon).
- Internal waves and tides present. K1, f, M2 dominate.
- *Enhancement near topography (2x orders of magnitude 150 m AB at Slope, 3x orders of magnitude 250 m AB at Axis).*
  - Subdiurnal and diurnal primarily along-slope (trapped to topography).
  - Most of the region supercritical to semidiurnal (downward), except canyon bottom (upward).
  - *Near-inertial attenuated at slope, enhanced in canyon.*
- *Enhancement seasonality varies between bands, but little inter-annually.*
  - Similar for diurnal and semidiurnal, but barotropic forcing is local for diurnal and remote for semidiurnal.
  - *Near-inertial forcing speculation through slab model and pumping mechanism.*
- State of continuum reflects topographic effects.  
  - Continuum elevated compared to GM (slope and amplitudes) near topography at both sites. Dissipation and diffusivities reflect this.
  - *Continuum seasonality suggests a cascade of energy from trapped subinertial motions at Slope, and canyon trapped semidiurnal motions in the canyon.*

**Questions for Discussion:**
- What forces the low-frequency subdiurnal motions?
- Where is the semidiurnal remote tidal forcing coming from?
- If near-inertial waves from the surface can't reach the slope, how is near-inertial flow forced in the canyon?
- Why do only certain wind events contribute to the near-inertial internal wave field?
- How do these topographic effects evolve along the canyon, and at different points along the slope?
- There appears to be little inter-annual variability, but is there longer-scale variability (decadal)?
- What would I have done differently? Instrument locations, etc.

------------------------------------------------

**Rough outline:**
- Mean currents (40hr low-pass)
  - Seasonal switch from poleward to equatorward upwelling favourable currents at Slope.
  - Little inter-annual variability.
  - Topographically guided. Mostly along-slope and along-canyon.
  - Slightly stronger near topography at Slope. Generally weak with subtle depth dependence and seasonality in the canyon.
  - Comparison and speculation: California Undercurrent, etc.
  
- Tidal currents and internal waves (40hr high-pass)
  - Presence of internal waves and tides of different frequencies, directions, and vertical structure. 
  - Strongest near to topography, at both sites.
  - Comparison and speculation: Internal tides generated at topography. Near-inertial internal waves generated at surface.
  
- Frequency response (PSD and rotary)
  - Little inter-annual variability.
  - Diurnal, inertial, and semidiurnal dominate, with certain sum frequencies present.
  - Depth-average spectra at Slope show diurnal = inertial < semidiurnal.
  - Depth-average spectra at Axis show inertial < diurnal < semidiurnal.
  - Subdiurnal motions are stronger at Slope than Axis.
  - Continuum appears whitened at Axis compared to Slope.
  - Comparison and speculation: Topography effects strength of constituents.
  
- Slope effects (depth-frequency)
  - Subdiurnal mostly along-slope, enhanced 150 m AB. 
  - Diurnal mostly along-slope, enhanced 150 m AB.
  - Near-inertial downward, attenuates 150 m AB.
  - Semidiurnal downward, enhanced 150 m AB. 
  - Continuum mix of components, enhanced 150 m AB.
  - Comparison and speculation: Sub-inertial trapped subdiurnal and diurnal signals. Downward near-inertial absorption by increased vertical shear in background flow near topography. Semidiurnal free and supercritical for most of slope region, leads to dominantly downward reflection. Continuum due to dissipative effects near topography, will be discussed further, later.
  
- Canyon effects (depth-frequency)
  - Subdiurnal mostly along-canyon, enhanced 250 m AB. 
  - Diurnal mostly along-canyon, enhanced 250 m AB.
  - Near-inertial along-canyon, enhanced 250 m AB.
  - Semidiurnal along-canyon (some cross-canyon), enhanced 300 m AB (100 m AB). 
  - Continuum mix of components, enhanced 300 m AB.
  - Comparison and speculation: Sub-inertial trapped subdiurnal and diurnal signals, as at Slope. Near-inertial canyon flow forced externally, radiates at depth due to interactions with canyon floor and walls. Semidiurnal free, but supercritical walls lead to downward reflection while subcritical floor leads to upward reflection, causing waves to be 'trapped' at depth. Continuum due to dissipative effects near topography, will be discussed further, later.
  
- Subdiurnal and tidal seasonality (integrated depth-band power)
  - Subdiurnal subtle seasonality, lull in summer. Similar at both sites.
  - Diurnal strong pulse in late-spring. Similar at both sites. In phase with barotropic surface levels, local forcing. 
  - Semidiurnal similar to diurnal at Slope, but less obvious in canyon. Out of phase with barotropic surface levels, remote forcing.
  - Comparison and speculation: Sub-inertial seasonality is unclear, will research. Diurnal likely tied to changes in stratification and regional mean currents. Semidiurnal similar to diurnal, but muddled in the canyon due to topographic effects (bouncing off walls/bottom).
  
- Near-inertial seasonality
  - Near-inertial intermittent pulses, strongest in winter and fall. More at Slope, mostly only fall pulses showing up in canyon. Pulses align with near-inertial forcing by certain regional wind events. 
  - Comparison and speculation: Near-inertial associated with particular wind events contributing to near-inertial energy pumping the mixed layer, with only the most significant events getting into the canyon.
  
- Continuum seasonality
  - Similar seasonality to the subdiurnal (and somewhat the diurnal) band at Slope, and the semidiurnal (and maybe a few near-inertial events) at Axis.
  - Slopes are whitened compared to the GM expected -2 for the open-ocean, increasingly so near topography.
  - c/GM amplitudes are generally heightened to many times the expected GM energy. Near to the slope, and everywhere in the canyon (though most of all near the bottom).
  - Dissipation estimate exceed 10^-8 W/kg near topography.
  - Diffusivities exceed 10^-3 m^2/s near topography.
  - Comparison and speculation: At Slope, the trapped subdiurnal (strong) and diurnal waves can only propagate along topography, causing significant dissipation through a cascade of energy from low to high frequency motions. Similarly, at Axis, the strong 'canyon trapped' semidiurnal signal shows significant topographic interaction, and hence high rates of dissipation contributing to high-frequency motions.

**Comment by jklymak** [comment]
These look great @kurtisanstey - to think about though - you are not going to publish a paper with 52 conclusions, so which of this list are the new and interesting science?

**Comment by kurtisanstey** [comment]
@jklymak thanks! I added the main points I want to focus on, and questions, at the top.

**Comment by kurtisanstey** [comment]
- Expanded outline w/ figures. Still in progress, about 1/2 done (mostly need to finish figures and restructure a bit more around my three 'stories'). When finished should be clear, no notes, all figures 'ready' to tell these stories. 
- Will live in documents folder of main directory.
- Also linked here, in readme, and at the top of this issue:
https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Thesis_Outline.pdf

**Comment by kurtisanstey** [comment]
@jklymak 

https://github.com/kurtisanstey/project/blob/master/documents/Anstey_Thesis_Rough.pdf

I've uploaded the updated thesis document. It's certainly just a draft, as you said, and will still need _many_ rounds of revisions. I do not consider this defendable or publishable, at all (I still have many updates and changes to make, yet). However, I feel it's getting close to having most of the content in there, in rough/outdated/OK form or otherwise!

To start, perhaps you can skim the document (no close reading necessary!) next week and give me some general opinions or suggestions? 

I'll pull some updates for the remaining GitHub issues out of the document, this weekend, so we can discuss them more clearly at our meeting. Looking forward to chatting with you!

**Comment by kurtisanstey** [comment]
- [ ] Pitch stories in Intro/Theory, then emphasise telling those stories throughout (including plots).
- [ ] p.18/19 discuss spectra in logical order and expand discussion, mention different lines are different years.
- [ ] What are the questions that go along with each story?
- [ ] Cut wordiness.
- [ ] WKB scaling for noise floor.
- [ ] Look at JGR for style guide.
- [ ] UVic thesis template.

**Comment by kurtisanstey** [comment]
Archiving for records. New issue re revisions.
