### ISSUE TITLE
Mean-flow in lower canyon

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#48]
- [x] Plots that show any variability in this flow.
- [x] Questions that arise.
- [x] What have others seen in canyons? (Kunze, Allen, etc.)
-------------------
- Plots show along-canyon low-pass velocities through depth (top) and in the lower canyon (centre), for each year. 
- Annual mean velocities and 2-week rolling mean velocities (bottom) are taken within the dashed lines (~700 - 900 m depth). 
- Annual mean velocities in this depth range fluctuate within 0.007 - 0.010 m/s, positive up-canyon.
- 2-week rolling mean velocities (bottom) also indicate that flow in this depth-range is consistently up-canyon (positive), with no obvious seasonality or inter-annual variability.
- Question: Why is this up-canyon flow restricted to a very specific depth range (between ~ 700 - 900 m depth)?
- Question: Why does the near-bottom flow appear to be opposite (down-canyon)?
--------------------
- Cabrera et al. (2018) found seasonally consistent up-canyon flow in a similar depth range (70 - 300 m AB) and of similar magnitude (~ 0.010 m/s) during a biological study at Barkley Canyon Axis in 2013-2014. They also found consistent down-canyon flow near the bottom (using a 2 MHz ADCP), suggesting a circulation cell within the canyon.
- Chauvet et al. (2018) also found seasonally consistent down-canyon BBL currents of about 0.010 m/s, possibly attributed to turbidity currents that are typically within 50-60 m AB, in a biological study in Barkley Canyon from 2012-2015 .
- Xu and Noble (2009) found that Monterey Canyon typically sees up-canyon mean-flow at depths greater than a few hundred metres. They also attribute near-bottom down-canyon flow to turbidity currents or river-flood-induced underflows. They found that mean-flow in canyons is largely depth and topographically dependent; one site at similar depth and scale to Barkley Canyon Axis showed similar up-canyon mean-flow above a ~60 m down-canyon bottom layer. These up/down-canyon mean flows are fairly consistent as they are typically driven by long-term cross-shore pressure gradients due to along-shelf currents; the long-term nature of the forcing tends to mean that monthly and annual averages of current layers generally maintain the same sign/direction.
- Question: Could the Juan de Fuca Strait produce something like a river-flood-induced underflow down Barkley Canyon, or is turbidity a more likely explanation for the down-canyon near-bottom flow?
---------------------
![image](https://user-images.githubusercontent.com/57200139/137225580-834f4a90-095d-43a6-9ce8-cbc0bc114910.png)
![image](https://user-images.githubusercontent.com/57200139/137225639-cf003d26-37d9-4b87-90ce-3b28182c5a18.png)
![image](https://user-images.githubusercontent.com/57200139/137225657-5ac88f68-75f7-4514-a3ec-4dcd6660d408.png)
![image](https://user-images.githubusercontent.com/57200139/137225672-4cc72461-2c37-4a2d-bd77-2c82e793f3f0.png)

**Comment by kurtisanstey** [comment]
@jklymak 

See above comment for a start on the up-canyon mean flow at Axis.

**Comment by jklymak** [comment]
Can you zoom in on one or two regions time.  It really seems there is a sense of propagation to these....

**Comment by kurtisanstey** [comment]
@jklymak 

- Plot 1 shows Jan-Mar and Plot 2 shows Jun-Aug.
- There appears to some upward propagation of the positive velocities. 
- Some appear to form at the bottom and strengthen as they move upward.
- There looks to be periodicity of about a week, and/or less.
- Question: Why do they strengthen away from the bottom? Some sort of shear effect?
- Question: Why is the apparent periodicity a few days to a week? This seems to be odd timing.
- Hotchiss and Wunsch (1982) found evidence of upward propagation in internal wave driven near-bottom up-canyon mean flows (Hudson Canyon). They claim the flows must develop upward propagation as they move up the canyon, to account for the bottom slope. They also mention these flows being partially driven by long-term large-scale quasi-geostrophic flows along the canyon mouth that have periods of > a few days. 
- Petruncio et al. (1998) found evidence of shoreward progressive internal wave driven flows with energy shoaling towards shore at an angle similar to the angle of the canyon floor, though these were generally of semidiurnal period.
------------------
![image](https://user-images.githubusercontent.com/57200139/137366559-83166d24-c78c-4205-af8a-fa80fb13d069.png)
![image](https://user-images.githubusercontent.com/57200139/137366584-466d3bc9-d5b3-45e6-9104-4e379ecf628d.png)

**Comment by jklymak** [comment]
Hi Kurtis,  Great job finding those references.  I do wonder if this is an example of "tidal rectification" where the tidal flow is non-linear, and there is a low-frequency component that comes from the modification of the "triangle" wave of the flow.  If it is just tidal rectification, though, the total transport (top to bottom, side to side) should be zero.  Even if you include the deep data, does this get driven to (almost) zero total transport?

**Comment by kurtisanstey** [comment]
@jklymak 

- As a rough estimate of total transport (along-canyon), if I extend the range (between dashed lines) for the annual mean velocity to include the deep data (650 m - bottom) the values for each year are approximately halved (0.004 - 0.005 m/s). 
- From one of Garrett's lectures on tidal rectification, in an observational situation with friction, etc. on a sloping bottom, the tidal rectification should result in an upper flow that follows a pressure gradient up-slope (in our case, up-canyon), with reversed flow near the bottom - if the U forcing is great enough. The net-flow would be slightly up-slope, even including the deep data, unless I misunderstand. It was only a brief lecture and didn't get into any triangle waves, net-zero transport, etc.

**Comment by kurtisanstey** [comment]
- Try to find a connection for the odd periodicity.
- [x] Spring-neap comparison?
- [x] Semidiurnal band forcing?
- [x] Slope low-pass currents?
--------------------------
- From the _**rough**_ qualitative comparison, below, there are no obvious similarities in periodicity that may indicate forcing. Shown is a two month period with the depth-mean along-canyon low-pass velocities (black), surface spring-neap levels (blue), along-slope depth-mean low-pass velocities (orange), and along-canyon depth-mean semidiurnal power (green).
![image](https://user-images.githubusercontent.com/57200139/138804232-da5daa88-85b7-4d1f-aab0-8ae5282a0e3e.png)
- Zoomed out to 6-month and annual periods there is still no obvious relationship.
![image](https://user-images.githubusercontent.com/57200139/138804778-52d525d8-f342-401d-b9e7-0e05198f15e7.png)
- [x] Finish write-up and plots in thesis.
