### ISSUE TITLE
Axis75 high-frequency noise

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#50]
Continuum velocity snapshot - (bandpass > 1.2e-5 Hz, entire hump) and (bandpass 1.2e-5 to 1.8e-5, first spike)):
<img src="https://user-images.githubusercontent.com/57200139/141184456-1eab8674-9026-4403-96cf-ab5c2c5b34e9.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/141188966-9ec5f81e-10b5-43b2-926c-1288174c4ec2.png" width="400">

The 'spike' contains much of the bad data, but not all. Obviously the 'hump' is contains bad data, in general. Bad ping in 15-min averaging?

**Comment by kurtisanstey** [comment]
- [ ] Bad pings in some bins; 15-min average data can be screened using correlation thresholds.
- [ ] Hump gets worse above 900 m; appendix showing every 25m?
- [ ] Does the hump even affect continuum range below 680 m? It doesn't appear to. Remove upper depths and upper frequencies from plots?

**Comment by kurtisanstey** [comment]
- [x] Hump gets worse above 900 m; appendix showing every 40m?
- Based on continuum amplitude and slope, the hump only affects continuum range above -680 m.
- Hump present through depth at frequencies above 1.2e-4 Hz.

Annual PSD for appendix - may affect continuum range _above_ -680 m:
<img src="https://user-images.githubusercontent.com/57200139/142139875-5da4d765-f992-4826-a0a3-de12fa5ab4f4.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142139917-efb131be-17e7-4c88-9c30-5d05236abf89.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142139958-b0fb6fc2-e63d-45f0-a2d3-3786666d0058.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142140000-49fc7a6f-0c35-4ac2-97cc-6a2d577099c1.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142140044-7cb2eeb3-2bbb-4ff1-8de4-724b0cd43c9f.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142140085-bdab3f24-a921-44d7-9fa5-cc06166acf4d.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142140134-4c5a1874-4fb6-44d7-a5ec-77be53dd783a.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142977222-f01ea3e4-0c78-477b-8c6f-295ed064ee8c.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142140196-6cae9d93-e945-44e5-a716-be1a2f4801fc.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142140322-42b2feab-670e-4d42-a16f-2fc1cdd6aeb2.png" width="400">

**Comment by kurtisanstey** [comment]
**Raw vs 15-min data, for Oct 10, 2013**

u:
![image](https://user-images.githubusercontent.com/57200139/142274483-5add551c-b8d1-44e0-9c52-801c230e68a5.png)
![image](https://user-images.githubusercontent.com/57200139/142274416-f187327b-b93c-47b7-993e-bc67c352d57a.png)

Mean Backscatter:
![image](https://user-images.githubusercontent.com/57200139/142273302-603c0e3c-ce56-4ed6-bf83-398ceb892c73.png)
![image](https://user-images.githubusercontent.com/57200139/142274696-8b5326d2-ddd4-4d19-bb91-72d0f65f0374.png)

Beam intensity:
![image](https://user-images.githubusercontent.com/57200139/142270994-b7d2f959-70ba-4d00-8bb2-76f08dced5c4.png)
![image](https://user-images.githubusercontent.com/57200139/142274716-0f80f9ab-e1ab-4fa4-b528-4ccf558f1acd.png)

Beam correlations:
![image](https://user-images.githubusercontent.com/57200139/142271926-f4e88714-9f46-40fa-9458-54db94da23de.png)
![image](https://user-images.githubusercontent.com/57200139/142274765-813ecd3b-6e8c-4d52-9523-53c05d0bf27c.png)

**Comment by kurtisanstey** [comment]
- [x] Smooth one day (Oct 10) of raw data to 15-minutes using both np.convolve (450 pt box car filter / 450 so sums to 1) and ds.coarsen and see how they compare with each other and ONC 15-minute data.
- Using xarray coarsen reproduces the ONC 15-minute data exactly (they probably used this function)
- Using numpy convolution reproduces the ONC 15-minute data with gaps where NaNs were present in the raw data. 

Raw (2-second, ONC):
![image](https://user-images.githubusercontent.com/57200139/142274483-5add551c-b8d1-44e0-9c52-801c230e68a5.png)
Averaged (15-minute, ONC):
![image](https://user-images.githubusercontent.com/57200139/142274416-f187327b-b93c-47b7-993e-bc67c352d57a.png)
Coarsened (15-minute, xarray from raw):
![image](https://user-images.githubusercontent.com/57200139/142925888-209c75be-c9a0-4741-98b9-0eb454777ba4.png)
Convolved (15-minute, numpy from raw):
![image](https://user-images.githubusercontent.com/57200139/142937084-5bf2e77c-6100-4a6c-9494-4f10fcea34e5.png)

---------------------

- [x] PSD of raw data to see if hump present.
- PSD of two months of raw data show that the hump and spikes are present. **_They are not a result of averaging_**.
- As with the 15-minute data, there is little effect on the specific continuum range below the threshold depths (see end of this comment). 

Raw PSD for appendix:
<img src="https://user-images.githubusercontent.com/57200139/142965134-11009dac-165e-46a5-892c-9193f8e83a68.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142975646-7ab2fbdf-59a7-4325-822b-81b654cd4134.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142975705-a36606e3-ce19-4ba7-bfae-e1dde2d3a1ba.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142975743-77ec139b-1c55-408f-a2db-92bc2877bc17.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142976454-e5c0e6db-79c6-47d4-835a-408fed7f8671.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142976482-c6922562-0fac-4efc-b05a-c7bb2b3ebc04.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142976507-fbb1ac4e-8722-480d-9d23-418278815c7e.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142976532-13a5d32b-5fc0-4335-a0ea-587f55dacff3.png" width="400">
<img src="https://user-images.githubusercontent.com/57200139/142976572-873df64e-7a43-48fa-afbf-071c04aefbb7.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142976619-8fb6bb4d-c2f2-4e68-8396-841e9981fe89.png" width="400">

---------------------

- Hump only 'goes away' at lower depths because the continuum amplitude rises to conceal it, seen in the 'zoomed out' PSD.
- There is also a very notable spike at 3e-3 Hz, that diminishes with depth.

'Zoomed out' raw PSD:
<img src="https://user-images.githubusercontent.com/57200139/142978427-77868e4c-690b-4d97-8893-67828e3d28fd.png" width="400"><img src="https://user-images.githubusercontent.com/57200139/142979127-82bb0896-b2a2-4525-b96e-ef9024114005.png" width="400">

----------------------

- [x] Evaluate 15-min data for corr. and intensity thresholds using ds.where, see if significant portion of deep data is affected.
- Echo intensity is best for evaluating noise, as ds.where function begins eliminating data with just a slight threshold increase. Raw data colour bars were set to 55 - 120 counts, and significant data is eliminated at a threshold of just 65.
- Correlation is more difficult to assess, as significant data is not eliminated until a very high threshold of 120 counts, where raw data colour bars were set to 75-130. 
- From both variables it is obvious that most of the 'bad' data is above -700 m, and rarely dips below this level.

![image](https://user-images.githubusercontent.com/57200139/142987167-71b96ed8-e913-4ed1-81a7-3cd5810c965d.png)
![image](https://user-images.githubusercontent.com/57200139/142987047-c941d727-e113-4ae5-b88e-0e35db6a758b.png)

![image](https://user-images.githubusercontent.com/57200139/142987230-6ba775b5-8158-44d9-b3db-7169373cf6d7.png)
![image](https://user-images.githubusercontent.com/57200139/142987072-501bb0f8-1c68-4975-a8e0-5c4da3ba2e32.png)

**Comment by kurtisanstey** [comment]
@jklymak 

See comment directly above this one for updates on data quality. If there are too many plots or the comments are tough to follow, we can discuss on Wednesday.

**Comment by jklymak** [comment]
@kurtisanstey That looks fine.  What happens when you combine these two into a flag on the velocity?  It looks like not a lot is gained from screening on full res versus 15 mintue averages, which is good.

**Comment by kurtisanstey** [comment]
- [x] Check long-term raw data for threshold consistency.

2 months screened intensity (raw):
![image](https://user-images.githubusercontent.com/57200139/143091081-3e726d57-5c1b-4b42-801d-466b5b915a4f.png)

----------------------

- [x] Combine corr. and intens. threshold data to make a 'flag' for the velocity data, see how it looks.
- Need to check long-term threshold values for better screening.
- Preliminary test of one day of 15-minute data results in a velocity screen (values of 1 or NaN, only) that could be applied as such:

Screen:
![image](https://user-images.githubusercontent.com/57200139/143139401-df13b1d0-33ba-4dfe-859a-c997f495a666.png)
Velocity:
![image](https://user-images.githubusercontent.com/57200139/143139461-9d3822ab-c4f2-46ac-8f45-823005c8011f.png)
Velocity after applying screen:
![image](https://user-images.githubusercontent.com/57200139/143140185-a7ebf765-9673-4d6c-901a-a1061e523cb4.png)

**Comment by kurtisanstey** [comment]
- [x] Check ds.coarsen for number of good data points per window.
- Coarsen function does not return # of good data points per window (checked xarray info and source code). It uses the 'mean()' function with skipna=True to determine window value. If set to skipna=False convolves data exactly as np.convolve(), with NaN for windows containing NaN. skipna() and np.convolve() both do not have a counter for # of good data points per window.
- [x] Check long-term 15-minute data for threshold consistency, decide how to cut data (mask or cut depth). Use percent good vs depth to determine good cut-off depth.
- Percent good vs depth for two years of 15-min data suggests that an echo intensity threshold of 65 and/or correlation threshold of 115 are ideal for screening data, and that threshold depth is fairly consistent through time.
- For these threshold values, there is steep step-like jump from 20% to 90% between -600 and -700 m.
- Propose cutting plots at -600 m, with analysis only below -700 m.
- Some seasonal variation of good data in fall (more bio scatterers higher in water column, so better reflection).
- [x] Cut plots at -600 m, and analysis line at -700 m? Why not just cut at -700 m?
- [x] Update writing with details.

![image](https://user-images.githubusercontent.com/57200139/143729706-7c6485e8-45bf-4c55-89c2-0b71d7a63722.png)
![image](https://user-images.githubusercontent.com/57200139/143534645-4a426012-dc20-40ff-a296-43bd32ebc83e.png)
![image](https://user-images.githubusercontent.com/57200139/143729257-26e0723d-d50b-4ce2-af1d-3ab8a19003b5.png)

**Comment by kurtisanstey** [comment]
Updated in writing. Archiving for reference.
