### ISSUE TITLE
Spectral shoulder

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#54]
- [x] Investigate near N spectral humps, this resolution data is pretty unprecedented over such a long period.
- [x] More research into spectral shoulder (more recent than D'Asaro?). Can't find much else!
- Pinkel (1975) refers to the prominent near-N peak as internal wave 'ringing', and ascribes it much of the observed high-frequency energy.
   - Observed to widen with depth as N(z) decreases.
- Leder (2002) builds on the work of Sabinin (1966), Pinkel (1975), Kase and Clarke (1978), Kase and Siedler (1980), and Levine et al. (1983), and determines that the near N spectral 'shoulder' is a result of an enhanced cascade of energy due to resonant wave-wave interaction (in their study mostly due to NI input by wind events) into the internal wave continuum occurring above the 'resonant' buoyancy frequency - essentially the depth-mean value of N below the buoyancy variable thermocline. 
   - Leder's depth-mean N below the thermocline was 3 cph, and they observe a prominent spectral shoulder at this frequency. 
   - Another (unlikely, according to Leder) theory is solitons, with periods of about 30+ minutes that can occur over shelf-break topography, forming in the troughs of semidiurnal internal tides during spring-tide generation periods. 
   -They attribute the departure from the GM progressive wave model to high-frequency motions (near N and higher) being better modelled as first mode standing waves, due to high-frequency waves within the thermocline being highly correlated and in phase (and backed up in this by Pinkel (1975)).
   - Kase and Clarke (1978) used GATE data to model this response, and their 'resonant' N was 2 cph (similar to Barkley Canyon), at which the spectral shoulder would form. 
- D'Asaro et al. (2007) observe a broad near-N peak, common in deep ocean observations, with weak correlation to the continuum or tidal range, and containing about 0.5 of the super-tidal energy, and analysis suggests little association with the occasionally observed solibores.
- Pinkel (2014) briefly speculates the high-wavenumber 'shoulder' could also be a product of sub-mesoscale motions.
- Alford (2016) associates this hump with NI IW due to enhanced high-frequency shear associated with wind-forced motions.
- [x] Check for M2 solitons near bottom? Need temperature data for M2 tidal amplitudes, or identify M2 velocity spikes upward of 1 m/s.
- There are no velocity events upward of 1 m/s (or even close to that) that would indicate solitons, at either site.
-----------------------
- [x] Get 1-minute data for investigation. 
- [x] Depth-band plots for depth and seasonal trends.
- There is evidence of the spectral shoulder at both Slope and Axis (75 kHz instruments), always peaking near N. 
- Also appears to widen with depth (just slightly, the effect noted by Pinkel possibly weakened by the WKB-scaling).
- The continuum amplitude also increases with depth, effectively masking the shoulder in the lowest ~100 m. 
- Shoulder depth-band power (1e-4 to 1e-3 Hz) shows some seasonality and depth dependence. 
- Pulses at Slope seem to recur each spring and fall.
- At Axis there is a lack of obvious seasonality in the two observable years (Axis 55 noise floor limits), though there may be additional activity in the fall.
- However, Axis data is poor, and there may processing artifacts at either site. 
- There appears to be an obvious correlation in shoulder and continuum depth-band power.

**Comment by kurtisanstey** [comment]
- [x] Check for solitons (not necessarily 1 m/s) as sharp spikes of velocity data with trail-off.
- Visual inspection of velocity data did not yield any obvious solitons.
- [x] Inspect continuum - shoulder frequency 'overlap', to make sure not getting some of the same data.
- Adjusted to [2.0e-4, 1.0e-3] Hz. There is still obvious visual correlation.
- [x] Compare seasonality with continuum to identify forcing.
- Fit is good at Slope.
- At Axis, there is a potential data issue. Only 2013 and 2014, and instruments appear to produce slightly different magnitudes of data after swap (difference in enabled beams, and speed of sound parameterization.
- If corrected with an offset, the Axis power law slope looks to be very similar to Slope, and an even better fit. 
- [x] PSD to see what happens during the different magnitude periods. 3-beam vs 4-beam issue between instruments?

**Comment by kurtisanstey** [comment]
- At Axis in 2013 and 2014, along-canyon 'Shoulder' PSD appears to show three distinct periods (circled blue, red, yellow) where power is multiplicatively higher or lower, coinciding with ONC instrument adjustments.
- I don't have enough good years to say if this is physical or instrument caused, but the timing is oddly coincidental.

![image](https://user-images.githubusercontent.com/57200139/147899314-bc0be27e-9730-40c7-835d-c324eab1483b.png)

- To investigate, raw 2-second spectra from Axis were depth averaged (within analysis depth range).
- The spectra were grouped based on ONC instrument deployment parameters:
   - Blue - 2013/01 to 2013/09, ADCP 1 was running with _all_ beams.
   - Red - 2013/09 to 2014/05, ADCP 1 received maintenance and was adjusted to exclude beam 2.
   - Yellow - 2014/05 to 2014/12 ADCP 1 was swapped for ADCP 2, already excluding beam 1.
- Spectral 'shoulder' is between the two green lines.

All:
![image](https://user-images.githubusercontent.com/57200139/147897434-69d41906-e179-4899-b330-99f82ef91fb4.png)

All (zoomed):
![image](https://user-images.githubusercontent.com/57200139/147897629-d185b135-ce8f-459c-b347-a88939a058c1.png)

- No individual features stick out as an obvious culprit, but there is an obvious offset in the PSD obtained during each period, with red being highest, yellow middling, and blue lowest - characterised in the time averaged plots.

Time averaged:
![image](https://user-images.githubusercontent.com/57200139/147898188-80555c47-f0cd-46af-9fbf-71c0c0c92927.png)

Time averaged (zoomed):
![image](https://user-images.githubusercontent.com/57200139/147898110-2fb2aec8-2ab3-4ab9-92d1-9de540911699.png)

---------------------

**Question for @jklymak:** 
How do I best approach discussing the offset Axis data for 2013 and 2014, in relation to the plot below (made from blue and yellow periods - red omitted):

- I think I should leave the data as is (keep the offsets and all three periods), do a separate fit for each period, and discuss the changing ONC instruments/parameters as part of the analysis.
- Or, I could multiply the yellow/red periods by factors determined from the time-averaged offsets above, to better align with the blue (blue spectra seem to be the 'tightest'). I would then do one fit for all the data, and discuss the adjustments. This seems a bit too hand-wavy to me. 
- Thoughts?

![image](https://user-images.githubusercontent.com/57200139/147899180-a0cdc53f-4fd7-4ccc-a2c6-78f9daa76f99.png)

**Comment by jklymak** [comment]
@kurtisanstey I guess this is probably a factor of 3 beam solutions having more variance than 4-beam solutions if the velocity field loses correlation on the scale of the beam separation.  So, its not as big a problem at lower frequencies, because the lateral scale of those motions is large.  However, at near-N, the lateral scale approaches the vertical scale and each beam can see quite different velocities.  A 4-beam solution will average that out over the horizontal pattern.  A 3-Beam solution will not average as much.  Further the 3-beam solution will have some preference in what it is looking at, given the direction of the three beams.

Todo: - check the orientation of the beams compared to the canyon and see if that story is consistent.
           - check if people have attenuation co-efficients for the variance depending on wavefield characteristics
           - check if the scaling holds in just the cross-canyon component, since that has less aliasing.

Overall I'm not sure what we can do about this - I think the shoulder is still significant and useful to look at.  We should just be careful about explaining the limitations.

**Comment by kurtisanstey** [comment]
- [x] Check the orientation of the beams compared to the canyon and see if that story is consistent (see Jody's comment, above).
- The only orientation data I could find is the magnetic compass heading. I'm assuming the beams are fixed on the instrument?
- 2013/01 to 2013/05 heading is 58 degrees.
- 2013/05 to 2014/05 heading is 104 degrees. However, it is 2013/09 where a beam was turned off and variance jumped up.
- 2014/05 to 2014/12 heading is 126 degrees. In 2014/05 the new instrument (still only three beams) has a variance drop.
- [x] Check if people have attenuation coefficients for the variance, depending on wavefield characteristics.
- Michida and Ishii (2000) compare 3-beam and 4-beam ADCP, and find that 3-beam solutions are prone to a 'scale-up' factor relative to misalignment with supposed heading.
- Alford (2003) applies a constant factor of 1.23 to align the variance of two different wind spectra, with the difference due to instrument processing differences (similar to our situation).
- Nystrom et al. (2007) extensively test 3-beam vs 4-beam ADCP in similar conditions and with different algorithms and parameterisations, and found that there will always be some inherent differences in the observed data.
- Kunze et al. (2012) have beam attenuation coefficients through depth for Monterey Canyon, but based on particulate concentration and not the wavefield.
- Kilbourne and Girton (2015) note a factor of 4 in variance difference due to instrument processing, but do not attempt to adjust the level.
- Thomson and Spear (2020) do a fairly deep analysis of ADCP variance adjustments due to changing instrument parameters, but do not determine attenuation coefficients.
- Contact ONC about variance adjustments? They have a 3-beam algorithm that is supposed to mitigate these effects. No.
- Contact Rick about 3-beam variance attenuation coefficients? He seems very knowledgeable on the parameterisation of ADCP. No.

**Comment by kurtisanstey** [comment]
- [x] Check which beam is forward (check RDI information)? Based on that, figure out which beams were turned off, and the direction of each beam during each period, to explain variance jumps (should be just red and yellow periods).
- Canyon is aligned a few degrees NNW at the Axis site; beam-3 is forward; beam angles are 20 degrees.
- ONC supplies both magnetic compass heading and offset heading. I checked the beam orientation for each, as well as with them combined (not sure which case indicates the true heading; my best guess is combined case, as it best maintains orientation).
- Rough sketches (below) each show orientations during the low (top), high (centre), and mid (bottom) variance periods. Sorry about the quality!
- Red lines highlight strongly along-canyon beam alignments.
- In the first case (magnetic compass heading), the high variance period has beam-1 and beam-4 aligned along-canyon, while the mid variance period has beam-2 and beam-3 aligned along-canyon. It is difficult to tell which of these periods is more aligned, as the topography is somewhat meandering.
- In the second case (offset heading), no period has beams aligned closely along-canyon.
- In the third case (magnetic compass + offset heading), both the high and mid variance periods have beam-3 and beam-4 aligned along-canyon. Again, it is difficult to tell which of these periods is more aligned, as the topography is somewhat meandering.
- The only other parameters that are different between these periods is speed of sound: 1500 for the low and high variance periods, and 1480 for the mid variance period.

Axis site:
<img src="https://user-images.githubusercontent.com/57200139/149584000-ef5bb397-a06b-4216-a99a-db88e1a8cc0a.png" width="500">

Magnetic compass heading:
<img src="https://user-images.githubusercontent.com/57200139/149593529-0ce441ff-8e98-43b2-8dc5-4d74db280245.jpg" width="500">

Offset heading:
<img src="https://user-images.githubusercontent.com/57200139/149593567-f02da3d0-718f-4048-8fb4-7e07389dc3b6.jpg" width="500">

Magnetic compass + offset heading:
<img src="https://user-images.githubusercontent.com/57200139/149593605-e4271c54-c271-4471-a650-2050256bbf68.jpg" width="500">

-----------------------

- [x] Redo Axis shoulder-dissipation fits for each variance period.
- Three of the power law slope estimates are very similar (~0.35), between sites, and all four estimates overlap within uncertainty (bootstrapped). 
- Results suggest a strong correlation with dissipation that does not differ between sites.
- [x] Discuss instrument adjustments and physical implications.

Shoulder-dissipation fits:
![image](https://user-images.githubusercontent.com/57200139/149875021-bbf596cd-8a37-45c5-bc55-a80cdc8cf6dd.png)

**Comment by kurtisanstey** [comment]
@jklymak 

See previous comment for updates.

**Comment by jklymak** [comment]
Sorry, which alignment corresponds to your red, yellow, and blue periods, as circled in the integrated variance plot above?

**Comment by kurtisanstey** [comment]
@jklymak on each page, the top alignment is for the first half of the blue period, the centre alignment is for the second half of the blue period to the end of the red period, and the bottom alignment is for the yellow period. 

The first page is based on the compass heading, the second page is offset heading, and the third page is them combined (I am assuming this is the correct one).

**Comment by jklymak** [comment]
I don't understand the addition in the third sheet. Why are there two such large numbers?  The compass should give you the heading of beam 3.  The only thing you need to know after that is if that heading has the magnetic declination of 20 degrees or so included in the heading or not.  (i.e. the north pole and the magnetic pole are 20 degrees apart at our position on the earth).  

But anyways, I think the point is that for the two deployments with higher variance they were only 20 degrees off from each other, so it would need to be a pretty asymmetric wave field to give such a large difference.  I think we can mention this possibility, and discuss it as possible future work, but outside our scope here.  To make sense of it you would have to go back to the raw data and process 2-beam solutions, and that is more work than seems necessary.

**Comment by kurtisanstey** [comment]
Thanks @jklymak! Very helpful. I'm also confused about the two large numbers; I was surprised to find the offset heading listed somewhere obscure after already looking at the compass heading.

- [x] Jody: But anyways, I think the point is that for the two deployments with higher variance they were only 20 degrees off from each other, so it would need to be a pretty asymmetric wave field to give such a large difference. I think we can mention this possibility, and discuss it as possible future work, but outside our scope here. To make sense of it you would have to go back to the raw data and process 2-beam solutions, and that is more work than seems necessary.
- [x] There _could_ be a difference in the high and mid variance periods for the spectral shoulder, but there is a coinciding drop in the continuum/dissipation and that range is not as affected, or at least not as much, by this issue (as suggested by the raw spectra). The continuum/dissipation fit _could_ be biased by the high-frequency issues noticeable in the spectral shoulder.
- [x] Ze says that whenever there is an Offset Heading available, that is the value to use. The Magnetic Compass Heading is typically inaccurate due to ferromagnetic interference from other instruments and the platform, so they use an ROV to check the true heading after the fact, and adjust data accordingly; the Offset Heading is the 'true' heading.

**Comment by kurtisanstey** [comment]
Archived for reference.
