### ISSUE TITLE
Deep average inflow (Axis)

### ISSUE THREAD

**Issue by kurtisanstey** [kurtisanstey/project#9]
Check process, using Euler, to confirm 30 degrees positive rotation to align v with along-slope (NNW) and u with cross-slope (ENE).

**Comment by kurtisanstey** [comment]
Confirmed via simple test case that u' = u*e^(-i*theta) where u' and u are horizontal velocity vectors, resulting in a positive (CCW) rotation of the horizontal axes, when theta is positive (in radians).

**Comment by kurtisanstey** [comment]
Not closed. Need to verify this velocity trend in other years.

**Comment by jklymak** [comment]
- look up papers with mean flow in Canyons...  (Monterey, Barkley?)

**Comment by jklymak** [comment]
- spring-neap cycle?

**Comment by kurtisanstey** [comment]
- [x] Mean flow in canyons? Monterey, Barkley.
- [ ] Spring/neap cycle? Indicates if this flow is driven by mixing.
- [x] Read more about this!

**Comment by kurtisanstey** [comment]
Allen et al. 2001 (Barkley Canyon) and Kampf 2018 (modelling) suggest that deep left-bounded along-shelf mean currents (southeastward for Barkley Canyon) enters but then turns cyclonically within the canyon, while mid-depth flow is advected up-canyon and upwelling occurs near the head. This doesn't work with my observation in terms of depth, and the fact that it is only seasonal (it is just the summer months where the mean currents switch to southeastward).

Kunze et al. 2012, Thomsen et al. 2012 both discuss canyon flows and do not mention any notable deep inflow and shallow outflow.

Xu & Noble 2009 find little correlation between their findings and those of other studies; though they **do** find an annual mean of deep inflow and shallow outflow, their findings do not match those of other studies in Monterey Canyon, or in Astoria Canyon. They suggest that canyon flow dynamics are quite complicated and variable, and can differ depending on the year and site. 

It is possible that this is the case in Barkley Canyon. However, only 2012 and 2013 Axis velocity data suggests this is a trend (see below), so I will check the 55 kHz ADCP that replaced (overlaps with) the 75 kHz instrument in later years, to confirm the trend (the data for the 55 kHz instrument isn't in nice NetCDF format so it may take some playing around with). 
https://github.com/kurtisanstey/project/blob/master/vel_plots/vel_axis_2012.pdf
https://github.com/kurtisanstey/project/blob/master/vel_plots/vel_axis_2013.pdf

**Comment by kurtisanstey** [comment]
- [ ] Is flow related to spring/neap cycle?
- [ ] Check additional years for this flow trend. This is in process.
- [x] Rework code for easier selection of instrument and desired period, and automated titles/filenames.
- [x] SciPy can read Matlab files > use xarray to convert to NetCDF for 55 kHz Axis data. 
- [x] ONC data for Axis 55 kHz in .mat and .csv format do not include velocity data. Requested this from ONC, and cc'd Steve. Mike Morley got back to me and we're working back and forth to make the data available to me (it's supposed to be there, but doesn't show up for regular accounts). Turns out it was a permissions issue, and quite a few folk were involved before things were resolved. I've downloaded the NetCDF for 2017-2019 and currently checking the data.
- [ ] Need to address data gaps due to adjustments in instrument depth values that cause horizontal banding, and temporal gaps that are too long to interpolate over. An example:
https://github.com/kurtisanstey/project/blob/master/plots/vel_plots/vel_Axis55_2018.pdf
However, 2017 shows some evidence of the deep inflow, shallow outflow:
https://github.com/kurtisanstey/project/blob/master/plots/vel_plots/vel_Axis55_2017.pdf

**Comment by kurtisanstey** [comment]
- [x] Improved bathymetry plot (with 100 m contours) for clarity. 
https://github.com/kurtisanstey/project/blob/master/archive/bathymetry/bathymetry.pdf
- [x] Fix depth issue to begin analysing 55 kHz data. If depths are close enough, load datasets separately. If not, load each and interpolate depths to only match the original dataset.
- [ ] Waiting for adjusted ONC data to confirm this process.
- [ ] Add inflow/outflow directional arrows to contour map (once depth issue resolved), and flow averages. Adjust velocity levels for clarity, and show extent of ADCP beam.
- [ ] Check if flow is related to spring/neap cycle, seasons, or annual trends.

**Comment by kurtisanstey** [comment]
Still waiting for 'fixed' Axis 75 kHz to confirm.

**Comment by kurtisanstey** [comment]
@jklymak 

With the updated Axis 75 kHz data, more appropriate depths for quality data from the Axis datasets, and the updated process to deal with data gaps in the Axis 55 kHz data, it is not possible to say if there is regular outflow in the upper depths of the canyon. The data that far up is unreliable. 

However, mean currents for all years do show a consistent, slight trend towards inflow in the lower/mid-depths. This agrees with Allen et al. 2001, Xu and Noble 2009, and Kampf 2018. It's consistency through the year suggests it's unrelated to either the spring/neap cycle or seasonal effects.

![image](https://user-images.githubusercontent.com/57200139/108414796-7f2a7000-71e1-11eb-8ca3-44a8729bbc66.png)
![image](https://user-images.githubusercontent.com/57200139/108414806-85b8e780-71e1-11eb-9c4e-722776a00b14.png)
![image](https://user-images.githubusercontent.com/57200139/108414835-923d4000-71e1-11eb-9042-d2c0a1434bb0.png)
![image](https://user-images.githubusercontent.com/57200139/108414907-a41ee300-71e1-11eb-8cd2-a91660848104.png)

- [ ] I'll plot up a directional arrow on my contour map, along with annual flow averages, for these years.
- [ ] Update Analysis document.

**Comment by kurtisanstey** [comment]
- [ ] Plot directional arrows on contour map.
- [ ] Show monthly/annual averages.
- [ ] Create better velocity plots that actual show something relevant to the point, e.g. adjust colour bars / no need to show residual in this case. Current plots are more for a general case (and even then, the residual get aliased too much).

**Comment by kurtisanstey** [comment]
This will be included in upcoming write-ups.
